#if !defined(__P_PSPR_H__)
#define __P_PSPR_H__

// stevepro
#include "doomenum.h"
#include "doomstruct.h"
#include "doomtype.h"
#include "doomvars.h"

// Basic data types.
// Needs fixed point, and BAM angles.
//#include "tables.h"

//
// Needs to include the precompiled
//  sprite animation tables.
// Header generated by multigen utility.
// This includes all the data for thing animation,
// i.e. the Thing Attributes table
// and the Frame Sequence table.



//dboolean P_CheckAmmo(weapontype_t weapon);
//void P_EquipWeapon(weapontype_t weapon);

//extern dboolean skippsprinterp;

#endif
